In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [3]:
data = load_iris()

In [4]:
dir(data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
df = pd.DataFrame(data.data, columns=data.feature_names)

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [8]:
df['flower'] = data.target

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X = df.drop("flower", axis =1)
y = df.flower

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [13]:
from sklearn.svm import SVC

In [14]:
model = SVC()

In [15]:
model.fit(X_train, y_train)
model.score(X_test, y_test)

1.0

In [16]:
from sklearn.model_selection import cross_val_score

In [17]:
cross_val_score(SVC(), X, y, cv = 3)

array([0.96, 0.98, 0.94])

In [18]:
cross_val_score(SVC(C =1.0, kernel='rbf', gamma='scale'), X, y, cv = 3)

array([0.96, 0.98, 0.94])

In [19]:
cross_val_score(SVC(C =1.0, kernel='linear', gamma='scale'), X, y, cv = 3)

array([1.  , 1.  , 0.98])

In [20]:
cross_val_score(SVC(C =10.0, kernel='linear', gamma='scale'), X, y, cv = 3)

array([1.  , 0.94, 0.98])