In [60]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [61]:
digits = load_digits()

In [62]:
 X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.33, random_state=42)

In [63]:
lr = LogisticRegression(max_iter = 7500)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9730639730639731

In [64]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9865319865319865

In [65]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9747474747474747

In [66]:
def get_score(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [67]:
get_score(lr, X_train, y_train, X_test, y_test)

0.9730639730639731

In [68]:
get_score(svm, X_train, y_train, X_test, y_test)

0.9865319865319865

In [69]:
get_score(rf, X_train, y_train, X_test, y_test)

0.9764309764309764

In [70]:
from sklearn.model_selection import KFold

In [71]:
fold = KFold(n_splits=3)

In [72]:
fold

KFold(n_splits=3, random_state=None, shuffle=False)

In [73]:
from sklearn.model_selection import StratifiedKFold

In [74]:
kf = StratifiedKFold(n_splits=5)

In [75]:
lr_score = []
svm_score = []
rf_score = []

In [76]:
for train_index, test_index in kf.split(digits.data, digits.target):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]
    lr_score.append(get_score(lr, X_train, y_train, X_test, y_test))
    svm_score.append(get_score(svm, X_train, y_train, X_test, y_test))
    rf_score.append(get_score(rf, X_train, y_train, X_test, y_test))

In [77]:
lr_score

[0.925,
 0.8777777777777778,
 0.9387186629526463,
 0.9331476323119777,
 0.8969359331476323]

In [78]:
svm_score

[0.9611111111111111,
 0.9444444444444444,
 0.9832869080779945,
 0.9888579387186629,
 0.9387186629526463]

In [80]:
rf_score

[0.9305555555555556,
 0.9138888888888889,
 0.9526462395543176,
 0.9637883008356546,
 0.9192200557103064]

In [81]:
np.mean(lr_score)

0.9143160012380068

In [82]:
np.mean(svm_score)

0.9632838130609718

In [83]:
np.mean(rf_score)

0.9360198081089447

In [84]:
from sklearn.model_selection import cross_val_score

In [85]:
cross_val_score(LogisticRegression(max_iter=7500), digits.data, digits.target, cv=5)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [86]:
cross_val_score(SVC(), digits.data, digits.target, cv=5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [87]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=5)

array([0.93888889, 0.89166667, 0.94986072, 0.97214485, 0.93593315])

-- Using parameter

In [89]:
cross_val_score(SVC(kernel = 'sigmoid'), digits.data, digits.target, cv=5)

array([0.87777778, 0.84444444, 0.89972145, 0.93314763, 0.84679666])

In [90]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=5)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

In [92]:
cross_val_score(SVC(C = 10), digits.data, digits.target, cv=5)

array([0.98055556, 0.95833333, 0.98328691, 0.98885794, 0.95821727])