# K_fold Intro

- It is a data partitioning strategy so that you can effectively use your dataset to build a more generalized model.

- K-Fold is validation technique in which we split the data into k-subsets and the holdout method is repeated k-times where each of the k subsets are used as test set and other k-1 subsets are used for the training purpose.

# - Importing all required libararies

In [4]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

- Creating object of the digit dataset

In [5]:
digits = load_digits()

- Here our dataset is in dictionary format 

In [6]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

# About dataset

- The columns available in our dataset is

In [8]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

- Description of dataset in contain as below

In [9]:
digits.DESCR

".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 1797\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttps://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of on pixel

- In below we have our all input values for dataset which we have to pass into our model

- It has all 8*8 digits input

In [10]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

- Below contain all about column name

In [12]:
digits.feature_names

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

- Images of each pixel value

In [14]:
digits.images

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

- Below contain the output of our input data

In [15]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

- Below The names of target classes.

In [16]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Applying train test split on dataset

In [18]:
 X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.33, random_state=42)

- Now we will first apply 3 different types of algorithm on our digits dataset and check accuracy of each algorithm
1. Logistic
2. SVC
3. Random forest

In [21]:
lr = LogisticRegression(max_iter = 7500)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9730639730639731

In [22]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9865319865319865

In [23]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9797979797979798

- Instead of run above 3 algorithm separately we creata a function in which we can pass any algorithm which gives us accuracy according to alogrithm.

-  Creating function in which we have to pass 5 parameter including algorithm 

In [24]:
def get_score(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

- Score according to the logistic algorithm

In [25]:
get_score(lr, X_train, y_train, X_test, y_test)

0.9730639730639731

-  Score according to the SVC algorithm

In [26]:
get_score(svm, X_train, y_train, X_test, y_test)

0.9865319865319865

-  Score according to the Random forest algorithm

In [27]:
get_score(rf, X_train, y_train, X_test, y_test)

0.9764309764309764

- importing Kfold from library

In [28]:
from sklearn.model_selection import KFold

In [29]:
fold = KFold(n_splits=3)

In [30]:
fold

KFold(n_splits=3, random_state=None, shuffle=False)

- As below we apply stratified fold on dataset

In [32]:
from sklearn.model_selection import StratifiedKFold

- Creating object of class StratifiedKFold

In [33]:
kf = StratifiedKFold(n_splits=5)

- Initialization of 3 empty list in which we append score of each algorithm according to number of split

In [34]:
lr_score = []
svm_score = []
rf_score = []

- Here we have define for loop which work till number of splits we provided

- As fold work index wise so we get values through its index in our training and testing sample

In [35]:
for train_index, test_index in kf.split(digits.data, digits.target):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]
    lr_score.append(get_score(lr, X_train, y_train, X_test, y_test))
    svm_score.append(get_score(svm, X_train, y_train, X_test, y_test))
    rf_score.append(get_score(rf, X_train, y_train, X_test, y_test))

- Below are the list after perfoming for loop for each algorithm

In [36]:
lr_score

[0.925,
 0.8777777777777778,
 0.9387186629526463,
 0.9331476323119777,
 0.8969359331476323]

In [37]:
svm_score

[0.9611111111111111,
 0.9444444444444444,
 0.9832869080779945,
 0.9888579387186629,
 0.9387186629526463]

In [38]:
rf_score

[0.9333333333333333,
 0.9055555555555556,
 0.9554317548746518,
 0.958217270194986,
 0.9192200557103064]

- For selection of best algorithm first we have to calculate its average and then we can choose one algorithm

In [39]:
np.mean(lr_score)

0.9143160012380068

In [40]:
np.mean(svm_score)

0.9632838130609718

In [41]:
np.mean(rf_score)

0.9343515939337668

- To avoid all above process we have below method

In [ ]:
Cross_val_score

- It is function to use during the testing and validation phase of your machine learning model development.
- This cross validation method gives you a better understanding of model performance over the whole dataset instead of just a single train/test split.

In [42]:
from sklearn.model_selection import cross_val_score

Parameter to pass for cross_val_score
- estimator = algorithm
- no. splits we want
- input 
- output

It work as below

- The dataset is split up according to these folds, where each fold has a unique set of testing data
- A model is trained and tested for each fold
- Each fold returns a metric for it's test data
- The mean and standard deviation of these metrics can then be calculated to provide a single metric for the process

- Below applying cross_val_score on different algorithm

In [43]:
cross_val_score(LogisticRegression(max_iter=7500), digits.data, digits.target, cv=5)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [44]:
cross_val_score(SVC(), digits.data, digits.target, cv=5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [45]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=5)

array([0.93611111, 0.88611111, 0.95543175, 0.96100279, 0.91086351])

-- Using parameter to check accuracy with different parameters

In [46]:
cross_val_score(SVC(kernel = 'sigmoid'), digits.data, digits.target, cv=5)

array([0.87777778, 0.84444444, 0.89972145, 0.93314763, 0.84679666])

In [47]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=5)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

In [48]:
cross_val_score(SVC(C = 10), digits.data, digits.target, cv=5)

array([0.98055556, 0.95833333, 0.98328691, 0.98885794, 0.95821727])