# Recommendation System

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("F:\PGDDS\PGD_Data_Science\csv_data\movies.csv")

In [5]:
df.head(1)

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity  ... runtime                                   spoken_languages  \
0  150.437577  ...   162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...   

     status                      tagline   title vote_average vote_count  \
0  Released  Enter the World of Pandora.  Avatar          7.2      11800   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   

                                                crew       director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...  James Cameron  

[1 rows x 24 columns]

In [6]:
df.shape

(4803, 24)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4775 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4391 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

In [8]:
df.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [9]:
df1 = df[['genres', 'keywords', 'tagline', 'cast', 'director']]

In [10]:
df1

genres  \
0     Action Adventure Fantasy Science Fiction   
1                     Adventure Fantasy Action   
2                       Action Adventure Crime   
3                  Action Crime Drama Thriller   
4             Action Adventure Science Fiction   
...                                        ...   
4798                     Action Crime Thriller   
4799                            Comedy Romance   
4800             Comedy Drama Romance TV Movie   
4801                                       NaN   
4802                               Documentary   

                                               keywords  \
0     culture clash future space war space colony so...   
1     ocean drug abuse exotic island east india trad...   
2            spy based on novel secret agent sequel mi6   
3     dc comics crime fighter terrorist secret ident...   
4     based on novel mars medallion space travel pri...   
...                                                 ...   
4798  united states\u2013mexico barrier legs arms pa...   
4799                                                NaN   
4800  date love at first sight narration investigati...   
4801                                                NaN   
4802               obsession camcorder crush dream girl   

                                                tagline  \
0                           Enter the World of Pandora.   
1        At the end of the world, the adventure begins.   
2                                 A Plan No One Escapes   
3                                       The Legend Ends   
4                  Lost in our world, found in another.   
...                                                 ...   
4798  He didn't come looking for trouble, but troubl...   
4799  A newlywed couple's honeymoon is upended by th...   
4800                                                NaN   
4801                           A New Yorker in Shanghai   
4802                                                NaN   

                                                   cast           director  
0     Sam Worthington Zoe Saldana Sigourney Weaver S...      James Cameron  
1     Johnny Depp Orlando Bloom Keira Knightley Stel...     Gore Verbinski  
2     Daniel Craig Christoph Waltz L\u00e9a Seydoux ...         Sam Mendes  
3     Christian Bale Michael Caine Gary Oldman Anne ...  Christopher Nolan  
4     Taylor Kitsch Lynn Collins Samantha Morton Wil...     Andrew Stanton  
...                                                 ...                ...  
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...   Robert Rodriguez  
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...       Edward Burns  
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...        Scott Smith  
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...        Daniel Hsia  
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...   Brian Herzlinger  

[4803 rows x 5 columns]

In [11]:
import warnings
warnings.filterwarnings('ignore')

In [12]:
df1.fillna(' ', inplace =True)

In [13]:
df.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [14]:
df1.isnull().sum()

genres      0
keywords    0
tagline     0
cast        0
director    0
dtype: int64

In [15]:
combined_feature = df1['genres'] + " " + df1['keywords'] + " " + df1['tagline'] + " " +  df1['cast'] + " " + df1['director']

In [16]:
combined_feature[0]

'Action Adventure Fantasy Science Fiction culture clash future space war space colony society Enter the World of Pandora. Sam Worthington Zoe Saldana Sigourney Weaver Stephen Lang Michelle Rodriguez James Cameron'

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
vectors = CountVectorizer()

In [19]:
feature_vectors = vectors.fit_transform(combined_feature)

In [20]:
feature_vectors.shape

(4803, 17318)

In [21]:
feature_vectors

<4803x17318 sparse matrix of type '<class 'numpy.int64'>'
	with 124266 stored elements in Compressed Sparse Row format>

In [22]:
feature_vectors.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
feature_vectors.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
vectors.get_feature_names_out()

array(['000', '007', '05', ..., 'zwigoff', 'zylka', '最后的舞者'], dtype=object)

In [25]:
import difflib

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
similarity = cosine_similarity(feature_vectors)

In [28]:
similarity

array([[1.        , 0.25253814, 0.10206207, ..., 0.        , 0.        ,
        0.        ],
       [0.25253814, 1.        , 0.10997148, ..., 0.05714286, 0.        ,
        0.        ],
       [0.10206207, 0.10997148, 1.        , ..., 0.        , 0.09072184,
        0.        ],
       ...,
       [0.        , 0.05714286, 0.        , ..., 1.        , 0.        ,
        0.04264014],
       [0.        , 0.        , 0.09072184, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.04264014, 0.        ,
        1.        ]])

In [29]:
similarity.shape

(4803, 4803)

In [30]:
movie = input("Enter the movie name : ")
movie

Enter the movie name : Iron man


'Iron man'

In [31]:
df['title']

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...                   
4798                                 El Mariachi
4799                                   Newlyweds
4800                   Signed, Sealed, Delivered
4801                            Shanghai Calling
4802                           My Date with Drew
Name: title, Length: 4803, dtype: object

In [32]:
movie_list = df['title'].to_list()

In [33]:
best_match = difflib.get_close_matches(movie, movie_list)

In [34]:
best_match

['Iron Man', 'Iron Man 3', 'Iron Man 2']

In [35]:
close_match = best_match[0]

In [36]:
close_match

'Iron Man'

In [37]:
df[df['title'] == close_match]

index     budget                            genres  \
68     68  140000000  Action Science Fiction Adventure   

                        homepage    id  \
68  http://www.ironmanmovie.com/  1726   

                                             keywords original_language  \
68  middle east arms dealer malibu marvel comic su...                en   

   original_title                                           overview  \
68       Iron Man  After being held captive in an Afghan cave, bi...   

    popularity  ... runtime  \
68  120.725053  ...   126.0   

                                     spoken_languages    status  \
68  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                               tagline     title vote_average vote_count  \
68  Heroes aren't born. They're built.  Iron Man          7.4       8776   

                                                 cast  \
68  Robert Downey Jr. Terrence Howard Jeff Bridges...   

                                                 crew     director  
68  [{'name': 'Sarah Finn', 'gender': 1, 'departme...  Jon Favreau  

[1 rows x 24 columns]

In [38]:
index_of_the_movie = df[df['title'] == close_match].values[0][0]

In [39]:
index_of_the_movie

68

In [40]:
similarity[68][:100]

array([0.12700013, 0.1026316 , 0.06913011, 0.03335187, 0.12320822,
       0.06788442, 0.14089399, 0.33882261, 0.03592106, 0.13340747,
       0.1796053 , 0.05354796, 0.070447  , 0.06558258, 0.18215302,
       0.03279129, 0.33882261, 0.06913011, 0.11503946, 0.11810772,
       0.13576885, 0.05986843, 0.03225806, 0.02993422, 0.05679618,
       0.        , 0.32258065, 0.12903226, 0.16971106, 0.070447  ,
       0.12320822, 0.37518324, 0.06071767, 0.22953904, 0.        ,
       0.14664712, 0.13116517, 0.03456506, 0.16675934, 0.19674775,
       0.03225806, 0.15401028, 0.        , 0.13116517, 0.03666178,
       0.10182663, 0.22718473, 0.14980118, 0.070447  , 0.        ,
       0.06788442, 0.11973687, 0.12320822, 0.1000556 , 0.06788442,
       0.07184212, 0.15677236, 0.07838618, 0.03829198, 0.13116517,
       0.03592106, 0.13826023, 0.07332356, 0.03126527, 0.19354839,
       0.03335187, 0.03279129, 0.10369517, 1.        , 0.0547791 ,
       0.13116517, 0.08466675, 0.16395646, 0.        , 0.10776

In [41]:
final_match = list(enumerate(similarity[index_of_the_movie]))

In [42]:
final_match 

[(0, 0.1270001270001905),
 (1, 0.10263160115815709),
 (2, 0.06913011298202835),
 (3, 0.033351867298253506),
 (4, 0.12320822072673948),
 (5, 0.06788442333021306),
 (6, 0.1408939907352694),
 (7, 0.33882260699853367),
 (8, 0.03592106040535498),
 (9, 0.13340746919301402),
 (10, 0.1796053020267749),
 (11, 0.0535479552601666),
 (12, 0.0704469953676347),
 (13, 0.06558258357839529),
 (14, 0.18215302221567486),
 (15, 0.032791291789197645),
 (16, 0.33882260699853367),
 (17, 0.06913011298202835),
 (18, 0.11503946170861017),
 (19, 0.11810771907149853),
 (20, 0.13576884666042613),
 (21, 0.05986843400892497),
 (22, 0.03225806451612904),
 (23, 0.029934217004462485),
 (24, 0.056796183424706485),
 (25, 0.0),
 (26, 0.3225806451612904),
 (27, 0.12903225806451615),
 (28, 0.16971105832553265),
 (29, 0.0704469953676347),
 (30, 0.12320822072673948),
 (31, 0.3751832396884334),
 (32, 0.060717674071891624),
 (33, 0.22953904252438354),
 (34, 0.0),
 (35, 0.14664711502135333),
 (36, 0.13116516715679058),
 (37, 0.0

In [43]:
from operator import itemgetter

In [44]:
sorted_match = sorted(final_match, key = itemgetter(1,0), reverse=True)

In [45]:
sorted_match

[(68, 0.9999999999999998),
 (79, 0.4237017130659009),
 (31, 0.3751832396884334),
 (16, 0.33882260699853367),
 (7, 0.33882260699853367),
 (26, 0.3225806451612904),
 (85, 0.3170114791543561),
 (182, 0.28575028575042866),
 (4401, 0.26940795304016235),
 (511, 0.26681493838602804),
 (94, 0.23346307108777456),
 (169, 0.22953904252438354),
 (101, 0.22953904252438354),
 (33, 0.22953904252438354),
 (203, 0.22718473369882594),
 (174, 0.22718473369882594),
 (46, 0.22718473369882594),
 (661, 0.21885688981825285),
 (242, 0.2155263624321299),
 (122, 0.2113409861029041),
 (618, 0.20131905799006777),
 (91, 0.20011120378952105),
 (607, 0.19674775073518588),
 (39, 0.19674775073518588),
 (166, 0.19596545041740515),
 (64, 0.19354838709677422),
 (126, 0.19050019050028574),
 (2442, 0.18759161984421674),
 (3623, 0.1872514715682846),
 (1740, 0.18481233109010925),
 (788, 0.18481233109010925),
 (353, 0.18338688097178615),
 (14, 0.18215302221567486),
 (4542, 0.1796053020267749),
 (131, 0.1796053020267749),
 (10,

- some for loop techniques by which we can access index and its score of similarity

In [46]:
n = 0
for i in sorted_match:
    n += 1
    if n<6:
        print(sorted_match[n])

(79, 0.4237017130659009)
(31, 0.3751832396884334)
(16, 0.33882260699853367)
(7, 0.33882260699853367)
(26, 0.3225806451612904)


In [47]:
for i in range(1,6):
    print(sorted_match[i])


(79, 0.4237017130659009)
(31, 0.3751832396884334)
(16, 0.33882260699853367)
(7, 0.33882260699853367)
(26, 0.3225806451612904)


- Below we get only index value for the similarity recommendation of the movies

In [48]:
print("Movie suggested for you : ")

for i in range(1,6):
    index = sorted_match[i][0]
    print(index)


Movie suggested for you : 
79
31
16
7
26


-  To access particular name of the movie from database

In [49]:
df.iloc[79]['title']

'Iron Man 2'

- As above we can implement it in our for loop

In [50]:
print("Movie suggested for you : ")

for i in range(1,6):
    index = sorted_match[i][0]
    print(df.iloc[index]['title'])

Movie suggested for you : 
Iron Man 2
Iron Man 3
The Avengers
Avengers: Age of Ultron
Captain America: Civil War
