In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv("F:\\PGDDS\\PGD_Data_Science\\csv_data\\netflix_titles.csv")

In [3]:
df.head()

show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson   
1      s2  TV Show          Blood & Water              NaN   
2      s3  TV Show              Ganglands  Julien Leclercq   
3      s4  TV Show  Jailbirds New Orleans              NaN   
4      s5  TV Show           Kota Factory              NaN   

                                                cast        country  \
0                                                NaN  United States   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN   
3                                                NaN            NaN   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India   

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min   
1  September 24, 2021          2021  TV-MA  2 Seasons   
2  September 24, 2021          2021  TV-MA   1 Season   
3  September 24, 2021          2021  TV-MA   1 Season   
4  September 24, 2021          2021  TV-MA  2 Seasons   

                                           listed_in  \
0                                      Documentaries   
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...

In [4]:
df.shape

(8807, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64 
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB


In [6]:
df1 = df[['type','title','director','cast','description']]
df1.head()

type                  title         director  \
0    Movie   Dick Johnson Is Dead  Kirsten Johnson   
1  TV Show          Blood & Water              NaN   
2  TV Show              Ganglands  Julien Leclercq   
3  TV Show  Jailbirds New Orleans              NaN   
4  TV Show           Kota Factory              NaN   

                                                cast  \
0                                                NaN   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...   
3                                                NaN   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...

In [7]:
df1.isnull().sum()

type              0
title             0
director       2634
cast            825
description       0
dtype: int64

In [8]:
df1.fillna(' ',inplace=True)

In [9]:

df1.isnull().sum()

type           0
title          0
director       0
cast           0
description    0
dtype: int64

In [10]:
combined_features = df1['title'] +' '+ df1['director'] +' '+ df1['cast'] +' '+ df1['description']
combined_features

0       Dick Johnson Is Dead Kirsten Johnson   As her ...
1       Blood & Water   Ama Qamata, Khosi Ngema, Gail ...
2       Ganglands Julien Leclercq Sami Bouajila, Tracy...
3       Jailbirds New Orleans     Feuds, flirtations a...
4       Kota Factory   Mayur More, Jitendra Kumar, Ran...
                              ...                        
8802    Zodiac David Fincher Mark Ruffalo, Jake Gyllen...
8803    Zombie Dumb     While living alone in a spooky...
8804    Zombieland Ruben Fleischer Jesse Eisenberg, Wo...
8805    Zoom Peter Hewitt Tim Allen, Courteney Cox, Ch...
8806    Zubaan Mozez Singh Vicky Kaushal, Sarah-Jane D...
Length: 8807, dtype: object

In [11]:
combined_features[0]

'Dick Johnson Is Dead Kirsten Johnson   As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.'

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
vectors = CountVectorizer()

In [14]:
feature_vectors = vectors.fit_transform(combined_features)

In [15]:
feature_vectors.shape

(8807, 53215)

In [16]:
feature_vectors

<8807x53215 sparse matrix of type '<class 'numpy.int64'>'
	with 350550 stored elements in Compressed Sparse Row format>

In [17]:
feature_vectors.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [18]:
vectors.get_feature_names_out()

array(['000', '007', '009', ..., '잡는다', '최강전사', '탄생'], dtype=object)

In [19]:
import difflib

In [20]:
similarity = cosine_similarity(feature_vectors)

In [21]:
similarity

array([[1.        , 0.05345225, 0.16699314, ..., 0.09548198, 0.08989331,
        0.21295885],
       [0.05345225, 1.        , 0.01673655, ..., 0.01913898, 0.        ,
        0.        ],
       [0.16699314, 0.01673655, 1.        , ..., 0.08968971, 0.04222003,
        0.22004401],
       ...,
       [0.09548198, 0.01913898, 0.08968971, ..., 1.        , 0.09656091,
        0.0457509 ],
       [0.08989331, 0.        , 0.04222003, ..., 0.09656091, 1.        ,
        0.04307305],
       [0.21295885, 0.        , 0.22004401, ..., 0.0457509 , 0.04307305,
        1.        ]])

In [23]:
similarity.shape

(8807, 8807)

In [43]:
show_name = input("Enter the show or movie name : ")
show_name

Enter the show or movie name : Blood & Water


'Blood & Water'

In [44]:
df['title']

0        Dick Johnson Is Dead
1               Blood & Water
2                   Ganglands
3       Jailbirds New Orleans
4                Kota Factory
                ...          
8802                   Zodiac
8803              Zombie Dumb
8804               Zombieland
8805                     Zoom
8806                   Zubaan
Name: title, Length: 8807, dtype: object

In [45]:
show_list = df['title'].to_list()

In [46]:
best_match = difflib.get_close_matches(show_name, show_list)

In [47]:
best_match

['Blood & Water', 'Blood Father', 'Blood Pact']

In [48]:
close_match = best_match[0]

In [49]:
close_match 

'Blood & Water'

In [50]:
df[df['title'] == close_match]

show_id     type          title director  \
1      s2  TV Show  Blood & Water      NaN   

                                                cast       country  \
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...  South Africa   

           date_added  release_year rating   duration  \
1  September 24, 2021          2021  TV-MA  2 Seasons   

                                         listed_in  \
1  International TV Shows, TV Dramas, TV Mysteries   

                                         description  
1  After crossing paths at a party, a Cape Town t...

In [70]:
index_of_the_show = df[df['title'] == close_match].index[0]

In [71]:
index_of_the_show

1

In [72]:
similarity[1][:100]

array([0.05345225, 1.        , 0.01673655, 0.03929887, 0.01822707,
       0.04591   , 0.04708236, 0.0348684 , 0.        , 0.08368274,
       0.02146694, 0.01380131, 0.06629935, 0.04708236, 0.        ,
       0.05020964, 0.08717101, 0.04591   , 0.06694619, 0.07377111,
       0.        , 0.0174342 , 0.03877834, 0.06332476, 0.        ,
       0.01801875, 0.05345225, 0.03194383, 0.01781742, 0.01822707,
       0.        , 0.06388766, 0.06761234, 0.01517942, 0.        ,
       0.06446584, 0.01657484, 0.01889822, 0.0334731 , 0.02020305,
       0.02760262, 0.01707469, 0.03524537, 0.08287419, 0.05020964,
       0.01889822, 0.04834938, 0.01673655, 0.04925318, 0.        ,
       0.05286805, 0.02857143, 0.01150109, 0.06121334, 0.02877772,
       0.040996  , 0.03060667, 0.03011693, 0.02562839, 0.01328032,
       0.0518563 , 0.01482499, 0.02760262, 0.03060667, 0.        ,
       0.02112886, 0.0225877 , 0.03380617, 0.        , 0.020498  ,
       0.0404061 , 0.01517942, 0.0311211 , 0.0360375 , 0.     

In [73]:
final_match = list(enumerate(similarity[index_of_the_show]))

In [74]:
final_match

[(0, 0.05345224838248487),
 (1, 0.9999999999999983),
 (2, 0.016736548175114458),
 (3, 0.03929887459459296),
 (4, 0.01822706541441223),
 (5, 0.04591000258371299),
 (6, 0.04708236154307583),
 (7, 0.03486840218772033),
 (8, 0.0),
 (9, 0.08368274087557229),
 (10, 0.021466939537054593),
 (11, 0.013801311186847081),
 (12, 0.06629935441317959),
 (13, 0.04708236154307583),
 (14, 0.0),
 (15, 0.05020964452534338),
 (16, 0.08717100546930083),
 (17, 0.04591000258371299),
 (18, 0.06694619270045783),
 (19, 0.07377111135633176),
 (20, 0.0),
 (21, 0.017434201093860166),
 (22, 0.038778336716474064),
 (23, 0.06332475868613036),
 (24, 0.0),
 (25, 0.01801874925391118),
 (26, 0.05345224838248487),
 (27, 0.031943828249996996),
 (28, 0.017817416127494958),
 (29, 0.01822706541441223),
 (30, 0.0),
 (31, 0.06388765649999399),
 (32, 0.06761234037828133),
 (33, 0.015179418517972908),
 (34, 0.0),
 (35, 0.06446583712203043),
 (36, 0.016574838603294898),
 (37, 0.01889822365046136),
 (38, 0.033473096350228916),
 (39,

In [75]:
from operator import itemgetter

In [76]:
sorted_match = sorted(final_match, key = itemgetter(1,0), reverse=True)

In [77]:
sorted_match

[(1, 0.9999999999999983),
 (4692, 0.1781741612749496),
 (1922, 0.1569078098447415),
 (6277, 0.14933067858931148),
 (5025, 0.14933067858931148),
 (3323, 0.14602041508114227),
 (1403, 0.14374722712498647),
 (6405, 0.1414213562373095),
 (679, 0.14098147537004826),
 (6788, 0.13944333775567924),
 (3516, 0.13389238540091566),
 (6052, 0.13259870882635919),
 (3493, 0.13259870882635919),
 (3492, 0.13259870882635919),
 (1162, 0.13259870882635919),
 (4483, 0.13134182066062372),
 (4202, 0.1301200097264711),
 (2960, 0.1301200097264711),
 (1260, 0.12893167424406085),
 (895, 0.12880163722232754),
 (3584, 0.12857142857142856),
 (1111, 0.12777531299998798),
 (7552, 0.1275894579008856),
 (5583, 0.1267731382092775),
 (3220, 0.1267731382092775),
 (8202, 0.12677313820927746),
 (6650, 0.12613124477737825),
 (6994, 0.12472191289246472),
 (5324, 0.1247219128924647),
 (8338, 0.12448440881789544),
 (5641, 0.12448440881789544),
 (2904, 0.12344267996967351),
 (1825, 0.12344267996967351),
 (8746, 0.123358790948792

In [78]:
n = 0
for i in sorted_match:
    n += 1
    if n<6:
        print(sorted_match[n])

(4692, 0.1781741612749496)
(1922, 0.1569078098447415)
(6277, 0.14933067858931148)
(5025, 0.14933067858931148)
(3323, 0.14602041508114227)


In [79]:
print("Show suggested for you : ")

for i in range(1,6):
    index = sorted_match[i][0]
    print(index)


Show suggested for you : 
4692
1922
6277
5025
3323


In [80]:
df.iloc[4692]['title']

'Mom'

In [81]:
print("Movie suggested for you : ")

for i in range(1,6):
    index = sorted_match[i][0]
    print(df.iloc[index]['title'])

Movie suggested for you : 
Mom
The Parkers
Beiimaan Love
Veronica
The Boy Who Cried Werewolf


In [ ]:
list(enumerate(similarity[index_of_the_show]))
sorted(final_match, key = itemgetter(1,0), reverse=True)

In [89]:
def reccomended(movie):
    movie_index = df1[df1["title"] == movie].index[0]
    print("index of movie is : ", movie_index)
    dist = similarity[movie_index]
    movie_list = sorted(list(enumerate(dist)),key=itemgetter(1,0),reverse = True)[0:6]

    for i in movie_list:
        #print(i[0])
         print(df1.iloc[i[0]].title)

In [90]:
reccomended('Dick Johnson Is Dead')

index of movie is :  0
Dick Johnson Is Dead
The Death and Life of Marsha P. Johnson
How to Be a Player
Earth's Natural Wonders: Life at the Extremes
Creating an Army of the Dead
The Last of the Schmucks


In [91]:
df1['type']

0         Movie
1       TV Show
2       TV Show
3       TV Show
4       TV Show
         ...   
8802      Movie
8803    TV Show
8804      Movie
8805      Movie
8806      Movie
Name: type, Length: 8807, dtype: object

In [98]:
def show_category(movie):
    index_of_the_show = df[df["title"] == movie].index[0]
    show_type = df.loc[index_of_the_show, "type"]
    return show_type

show_type = show_category('Vendetta: Truth, Lies and The Mafia')
if show_type:
    print(f"The show type is: {show_type}")

The show type is: TV Show


In [100]:
from operator import itemgetter

def recommend_and_show_category(movie):
    # Find the index of the given movie title in the movie DataFrame
    try:
        movie_index = df1[df1["title"] == movie].index[0]
        
        # Get the recommended movies based on similarity
        dist = similarity[movie_index]
        movie_list = sorted(list(enumerate(dist)), key=itemgetter(1,0), reverse=True)[:6]

        print("Recommended movies:")
        for i in movie_list:
            recommended_movie_title = df1.iloc[i[0]].title
            print(recommended_movie_title)

        # Get the category (type) of the given movie
        index_of_the_show = df[df["title"] == movie].index[0]
        show_type = df.loc[index_of_the_show, "type"]
        print(f"\nThe show type of '{movie}' is: {show_type}")

    except IndexError:
        print("Movie not found or insufficient data.")

In [101]:
# Example usage
recommend_and_show_category('Vendetta: Truth, Lies and The Mafia')

Recommended movies:
Vendetta: Truth, Lies and The Mafia
Kill the Irishman
Fear City: New York vs The Mafia
Drug Lords
The Seventies
Shiva: The Secret World Of Vedas City

The show type of 'Vendetta: Truth, Lies and The Mafia' is: TV Show


In [103]:
recommend_and_show_category('Dick Johnson Is Dead')

Recommended movies:
Dick Johnson Is Dead
The Death and Life of Marsha P. Johnson
How to Be a Player
Earth's Natural Wonders: Life at the Extremes
Creating an Army of the Dead
The Last of the Schmucks

The show type of 'Dick Johnson Is Dead' is: Movie
